name: Every minute cron job
on:
  schedule:
    - cron: '* * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Every minute job
        run: |
          curl --request POST \
          --url 'https://roundup-eight.vercel.app/api/task' \
          # --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'